meta:
  title: ReconHub | Interface documentation
  description: The best API documentation generator ever.
  siteUrl: https://developer-portal-starter.redoc.ly
  keywords: redocly developer portal, api portal starter, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo: ./static/logos/logo-reconhub-wordmark-white.svg
toc:
  enable: true
oasDefinitions:
  petstore: https://api.redocly.com/registry/bundle/test-goa/Test%20API/v1/openapi.yaml?branch=main
  petstore-v2: ./openapi/petstore.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - './static/fonts/noto-sans-display/style.css'
  - './static/fonts/monospace/style.css'
  - './static/css/variables.css'
  - './static/css/global.css'
  - './static/css/font.css'
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: Interface Docs
    page: developer-portal/index.md
  - label: Learn Center
    href: 'https://learn.reconhub.cloud'
  - label: ReconHub App
    href: 'https://app.reconhub.cloud'
  - search: true

footer:
  copyrightText: ReconHub by Abrantix
  columns:
    - group: Legal
      items:
        - label: Legal notice
          href: 'https://www.abrantix.com/en/legal-notice.html'
        - label: Privacy policy
          href: 'https://www.abrantix.com/en/privacy-policy.html'
    - group: Support
      items:
        - label: Support tickets
          href: 'https://learn.reconhub.cloud/portal/en/myarea'
